### ISSUE TITLE
Design Tweaks

### ISSUE THREAD

**Issue by tuckabelle** [CSIS-iLab/chinapower_wp#13]
- [x] Gray box style around in-article asides
  - [x] Implement on live site 
- [x] in-article experts styles (photo + name + caption) (i.e. How is China shaping the global economic order?)
  - [x] Implement on live site
- [x] Image fact styles (i.e. How is China shaping the global economic order?)
  - [x] Implement on live site
- [x] WATCH list (i.e. How is China shaping the global economic order?) - make this look like small "VIEW" icon in Data Sources
  - [x] Implement on live site
- [x] Homepage stats: background icon should have top padding
- [x] Link style change...
- [x] When there are no data sources, have "Cite this page" class change to 'col-md-8'
- [x] Change text color of text in pagination to black on hover (right now it's red)
- [x] Mobile: Tag archive title runs off side ([example](http://chinapower.csis.org/tag/trade/))
- [x] Featured Stat: Remove [stat] shortcode from dropdown
- [x] Remove "categories" from podcasts
- [x] is it possible to get the gradient fade on article post title to be dependent on the title itself? That and/or make the font size of the mobile titles a bit smaller
- [x] "Featured In" section on homepage: margins are not wide enough/do not match "Winner of" section 
- [x] Pagination: make buttons bigger on mobile. And if buttons go to second line, they overlap
- [x] Mobile Share doesn't have a close option on data repo page
- [x] Mobile Share doesn't have a close option on podcast page
- [x] Data Repo inline share using mobile styles
- [x] Data Repo Individual page add link to go back to data repo
- [x] Related content on posts with no further reading is too spaced out
- [ ] Wrap videos in `<div class="videoWrapper"></div>`
- [x] Featured podcast should only be first overall, not the first on each page
- [ ] There is an extra border above the first data repo item in Firefox
- [ ] Mobile: Copy tooltip doesn't disappear after clicking elsewhere
- [ ] Mobile: Data repo table view doesn't fit on screen
- [ ] Image hover: don't underline images like text

**Internet Explorer**
- [ ] On the home page, the bar with topics and podcasts is located on the photo instead of above it and the title of the piece corresponding to the photo is on the top left of the photo (on the bottom left on Google Chrome) and it is hard to read
- [ ] Because the links on the homepage to topics and podcasts and others are not above the photo, they move down the page when scrolling without any background. So it's just floating words

**Comment by jnschrag** [comment]
@tuckabelle For the padding on featured stat on the homepage, be aware that the height of the icon is icon specific. For example, the mobile icon is smaller than the ship icon, so the spacing is going to be different between them even though the overall height of the `<i>` element are the same.

<img width="373" alt="screen shot 2017-08-09 at 3 55 04 pm" src="https://user-images.githubusercontent.com/1896496/29141202-3552b712-7d1b-11e7-8938-a6720816f12c.png">
<img width="383" alt="screen shot 2017-08-09 at 3 55 22 pm" src="https://user-images.githubusercontent.com/1896496/29141203-355441a4-7d1b-11e7-912d-856194cc87df.png">
